### ISSUE TITLE
Application uses hardcoded path to /home

### ISSUE THREAD

**Issue by labkode** [owncloud/ocis-wopiserver#8]
This assumption breaks our deployment and we cannot test the application.

```
[15:02][root@cbox-ocisdev-03 (ocis_dev:box/ocis) ocis-wopiserver]# grep -ri '/home' .
./ui/app.js:      axios.get(tokenUrl, { params: { filePath: '/home' + filePath, fileId: fileId } })
```

The request should be send to: `/eos/user/g/gonzalhu/...` but is sent to `/home/eos/user/g/gonzalhu/...`

![image](https://user-images.githubusercontent.com/5175912/122770999-4d680980-d2a6-11eb-8175-2ca5c9559d4a.png)

This applies to any application/extension.
The application needs to use the configured webdav namespace.
The UI knows the good namespace as when clicking on "All files" the request is correct.
This boils down to harcoded paths in the app.

@kulmann could you point @wkloucek to the magic variable that encapsulate the files namespace so is used instead of `/home`?

**Comment by wkloucek** [comment]
I didn't find any place where Web needs the namespace setting since it only uses the WebDav API - which is aware of the namespace. Web only offers to configure the `homeFolder`, which is the Path where the user is brought to when he clicks the home icon. But this doesn't need to be qual to the namespace.

Therefore I switched to File IDs wich is easier -> see #https://github.com/owncloud/ocis-wopiserver/pull/10

**Comment by labkode** [comment]
@wkloucek let me take a look at that PR
